// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9AGgT5PAmmsY_yf5dTbUfOFTNv_3cGdw',
    appId: '1:713770988562:web:b5ab443d55fa963f1cd4cb',
    messagingSenderId: '713770988562',
    projectId: 'financ-fb935',
    authDomain: 'financ-fb935.firebaseapp.com',
    storageBucket: 'financ-fb935.appspot.com',
    measurementId: 'G-Q6S4NFG468',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dWEHgInJgRqm8Ym6_Hy58cS5M3RSzzY',
    appId: '1:713770988562:android:3e7d9ee5bc7728fd1cd4cb',
    messagingSenderId: '713770988562',
    projectId: 'financ-fb935',
    storageBucket: 'financ-fb935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCft8zeROEuMDJg5C7qEfZ3VqlMaI0Xy0k',
    appId: '1:713770988562:ios:69f33271683c10881cd4cb',
    messagingSenderId: '713770988562',
    projectId: 'financ-fb935',
    storageBucket: 'financ-fb935.appspot.com',
    iosClientId: '713770988562-sepre0qgdr30stok6s26154kha6siui8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCft8zeROEuMDJg5C7qEfZ3VqlMaI0Xy0k',
    appId: '1:713770988562:ios:e6838eea848f752b1cd4cb',
    messagingSenderId: '713770988562',
    projectId: 'financ-fb935',
    storageBucket: 'financ-fb935.appspot.com',
    iosClientId: '713770988562-00ogicfa4vviosse5dsgp0vm8990m1ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance.RunnerTests',
  );
}
